app/urls.py
from django.urls import path
from .import views

app_name = 'app'
urlpatterns = [

    #index
    path('',views.index_view, name='index'),
    
    #iniciar sesion
    path('login/',views.login_view, name='login_view'),
    path('login_post/',views.login_post, name='login_post'),
    #Cerrar sesion
    path('logout/',views.logout_, name='logout_'),
    
    #Crear usuario
    path('startup/',views.startup_view, name='startup_view'),
    path('startup_post/',views.startup_post, name='startup_post'),
    
    #Habilitar ciudadano
    path('habiCiuda',views.habiCiuda_view, name='habiCiuda_view'),
    path('habiCiuda_post',views.habiCiuda_post, name='habiCiuda_post'),

    #editar usuario
    path('editProfile',views.editProfile_view, name='editProfile_view'),
    path('editProfile_post',views.editProfile_post, name='editProfile_post'),
    
    #crear partido
    path('creaPart',views.creaPart_view, name='creaPart_view'),
    path('creaPart_post',views.creaPart_post, name='creaPart_post'),

    #consultar partidos
    path('consPart',views.consPart_view, name='consPart_view'),
    
    #consutar un partido
    path('consPart/<int:id>',views.consAPart_view, name='consAPart_view'),

    #crear individuo
    path('creaIndiv',views.creaIndiv_view, name='creaIndiv_view'),
    path('creaIndiv_post',views.creaIndiv_post, name='creaIndiv_post'),
    
    #consultar individuos
    path('consIndiv',views.consIndiv_view, name='consIndiv_view'),
    
    #consultar un individuo
    path('consIndiv/<int:id>',views.consAIndiv_view, name='consAIndiv_view'),
    
    #habilitar individuo
    path('aproIndiv_post',views.aproIndiv_post, name='aproIndiv_post'),

    #crear proceso
    path('creaPro',views.creaPro_view, name='creaPro_view'),
    path('creaPro_post',views.creaPro_post, name='creaPro_post'),
    
    #aprobar proceso
    path('aproPro',views.aproPro_view, name='aproPro_view'),
    path('aproPro_post',views.aproPro_post, name='aproPro_post'),

    #consultar un proceso
    path('consApro/<int:id>',views.consApro_view, name='consApro_view'),

    #afiliar individuo a partido
    path('afilIndi/<int:id>',views.afilIndi_view, name='afilIndi_view'),
    path('afilIndi_post',views.afilIndi_post, name='afilIndi_post'),
    
    #aprobar afiliacion
    path('aproAfil',views.aproAfil_view, name='aproAfil_view'),
    path('aproAfil_post',views.aproAfil_post, name='aproAfil_post'),

    #implicar individuo
    path('ImplicarIndi/<int:id>',views.ImplicarIndi_view, name='ImplicarIndi_view'),
    path('ImplicarIndi_post',views.ImplicarIndi_post, name='ImplicarIndi_post'),
]

corrupcion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')), #
]

app/templates/app/ImplicarIndi.html
{% extends "app/templateIn.html" %}

{% block Administrar %}
    {% if request.user.is_superuser == 0 %}
        <li style="display: none;" class="li-start"><a href="#">Administrar</a>
    {% else %}
        <li class="li-start"><a href="#">Administrar</a>
    {% endif %}
{% endblock %}

{% block contenido %}
<body>
    <div class="form-container">
        <div class="welcome-container">
            <span>Implicar Afiliado del partido en un proceso</span>
            <hr>
            <p>Nombre del Partido: <br>{{partido.nameP}}</p>
            <label for=""></label>
            
            <div class="forms">
                <form action="{% url 'app:ImplicarIndi_post' %}" method="post" id="form-log" class="form">
                    {% csrf_token %} 
                    <label for="">Afiliado</label>
                    <select name="afil_id" id="afil_id">
                        {% for afiliado in afiliados %}
                            <option label="{{afiliado.indiv_name}} {{afiliado.indiv_lastname}}">{{afiliado.afil_id}}</option>
                        {% endfor %}
                    </select>
                    <label for="">Proceso</label>
                    <select name="pro_id" id="pro_id">
                        {% for proceso in procesos %}
                            {% if proceso.active == 1 %}
                            <option label="{{proceso.title}}">{{proceso.id}}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                    <fieldset>
                        <label for="">Fecha de Implicación</label>
                        <input type="date" name="date_imp" id="date_imp">
                    </fieldset>
                    <fieldset>
                        <label for="">Acusación</label>
                        <input type="text" name="charges" id="charges">
                    </fieldset>
                    <fieldset>
                        <label for="">Culpable/Inocente</label>
                        <select name="guilty" id="guilty">
                            <option value="false">Inocente</option>
                            <option value="true">Culpable</option>
                        </select>
                    </fieldset>
                    <fieldset>
                        <label for="">Pena</label>
                        <input type="text" name="sentence" id="sentence">
                    </fieldset>
                    <fieldset>
                        <label for="">Comentarios</label>
                        <input type="text" name="commnts" id="commnts">
                    </fieldset>
                   <button type="submit">Enviar</button>
                </form>
            </div>
        </div>
    </div>
</body>
{% endblock %}

app/templates/app/aproAfil.html
{% extends "app/templateIn.html" %}

{% block Administrar %}
    {% if request.user.is_superuser == 0 %}
        <li style="display: none;" class="li-start"><a href="#">Administrar</a>
    {% else %}
        <li class="li-start"><a href="#">Administrar</a>
    {% endif %}
{% endblock %}

{% block contenido %}
<body>
    <div class="inf-container">
        <div class="inf">
            <span>Lista de Afiliaciones</span>
            <p></p>
            <table>
                <thead>
                    <tr>
                        <th>Partido</th><th>Individuo</th><th>ID</th><th>Estado</th>
                    </tr>
                </thead>
                {% for afiliacion in afiliaciones %}
                <tr>
                    <td>{{ afiliacion.part }}</td>
                    <td>{{ afiliacion.name }} {{ afiliacion.lastname }}</td>
                    <td>{{ afiliacion.id }}</td>
                    <td>
                        {% if afiliacion.active == True %}
                            Aprobado
                        {% else %}
                            No Aprobado
                        {% endif %}
                    </td>
                    <td>
                        <form method="post" action="{% url 'app:aproAfil_post' %}">
                            {% csrf_token %}
                            <fieldset>
                                <input type="text" name="id" id="id" style="display: none;" value="{{afiliacion.id}}">
                            </fieldset>
                            <fieldset>
                                <button type="submit" class="cons-Btn"><a>Cambiar Estado</a></button>
                            </fieldset>
                        </form>
                    </td>
                </tr>               
                {% endfor %}                
            </table>
        </div>
    </div>
</body>
{% endblock %}

app/templates/app/consAIndiv.html
{% extends "app/templateIn.html" %}

{% block Administrar %}
    {% if request.user.is_superuser == 0 %}
        <li style="display: none;" class="li-start"><a href="#">Administrar</a>
    {% else %}
        <li class="li-start"><a href="#">Administrar</a>
    {% endif %}
{% endblock %}

{% block contenido %}
<body>
    <div class="inf-container">
        <div class="inf">
            <span>Consultar Individuo</span>
            <p>Informacion del individuo</p>
            <table>
                <thead>
                    <tr>
                        <th>Apellidos</th><th>Nombres</th><th>Fecha de nacimiento</th><th>Cantidad de vistas</th>
                    </tr>
                </thead>
                        <tr>
                            <td>{{ info.indiv_lastname }}</td>
                            <td>{{ info.indiv_name }}</td>
                            <td>
                                {% if info.birthday %}
                                    {{ info.birthday }}
                                {% else %}
                                    Sin Información
                                {% endif %}
                            </td>
                            <td>{{ info.views }}</td>
                        </tr>               
            </table>
            <span>Lista de afiliaciones</span>
            <table>
                <thead>
                    <tr>
                        <th>Partido</th><th>Fecha de ingreso</th><th>Fecha salida</th>
                    </tr>
                </thead>
                        <tr>
                            {% if part.id %}
                                <td><a href="{% url 'app:consAPart_view' part.id %}">{{ part.nameP }}</a></td>
                                {% if afil.date_in %}
                                    <td>{{afil.date_in}}</td>
                                {% else %}
                                    <td>Sin datos</td>
                                {% endif %}

                                {% if afil.date_out %}
                                <td>{{afil.date_out}}</td>
                                {% else %}
                                    <td>Sin datos</td>
                                {% endif %}

                            {% else %}
                            <td>Sin afiliaciones</td><td>Sin datos</td><td>Sin datos</td>
                            {% endif %}
                        </tr>               
            </table>
            <span>Lista de procesos</span>
            <table>
                <thead>
                    <tr>
                        <th>Fecha inicio del proceso</th>
                        <th>Fecha fin del proceso</th>
                        <th>Titulo del proceso</th>
                        <th>Entidad</th>
                        <th>Monto</th>
                        <th>Comentarios proceso</th>
                        <th>Abierto/Cerrado</th>
                        <th>Acusacion</th>
                        <th>Culpable/Inocente</th>
                        <th>Pena</th>
                        <th>Comentarios Implicacion</th>
                    </tr>
                </thead>
                        {% for dato in lista %}
                        <tr>
                            <td><a href="{% url 'app:consApro_view' dato.pro.id %}">{{dato.pro.title}}</a></td>
                            <td>{{dato.pro.date_start}}</td>
                            <td>{{dato.pro.date_end}}</td>
                            <td>{{dato.pro.entity}}</td>
                            <td>{{dato.pro.howmuch}}</td>
                            <td>{{dato.pro.comments}}</td>
                            <td>{{dato.pro.state}}</td>
                            <td>{{dato.impl.charges}}</td>
                            <td>{{dato.impl.guilty}}</td>
                            <td>{{dato.impl.sentence}}</td>
                            <td>{{dato.impl.commnts}}</td>
                        </tr>
                        {% endfor %}                
            </table>
            <div class="btn-container">
                <button class="cons-Btn"><a href="{% url 'app:afilIndi_view' info.id %}">Afiliar individuo un partido</a></button>
            </div>
        </div>
    </div>
</body>
{% endblock %}

app/templates/app/consAPart.html
{% extends "app/templateIn.html" %}

{% block Administrar %}
    {% if request.user.is_superuser == 0 %}
        <li style="display: none;" class="li-start"><a href="#">Administrar</a>
    {% else %}
        <li class="li-start"><a href="#">Administrar</a>
    {% endif %}
{% endblock %}

{% block contenido %}
<body>
    <div class="inf-container">
        <div class="inf">
            <span>Consultar Partido Político</span>
            <p>Informacion del partido</p>
            <table>
                <thead>
                    <tr>
                        <th>Nombre del partido</th><th>Cantidad total de procesos</th><th>Cantidad de procesos culpables</th><th>Cantidad de vistas</th>
                    </tr>
                </thead>
                        <tr>
                            <td>{{ info.nameP }}</td><td>{{procesos}}</td><td>{{procesos_c}}</td><td>{{ info.views }}</td>
                        </tr>               
            </table>
            <span>Lista de afiliados</span>
            <table>
                <thead>
                    <tr>
                        <th>Apellidos</th><th>Nombres</th><th>fecha de ingreso</th><th>fecha de salida</th>
                    </tr>
                </thead>
                {% for individuo in lista_indv %}
                    <tr>
                        <td><a href="{% url 'app:consAIndiv_view' individuo.indiv_id %}">{{individuo.indiv_lastname}}</a></td>
                        <td><a href="{% url 'app:consAIndiv_view' individuo.indiv_id %}">{{individuo.indiv_name}}</a></td>     
                        {% if individuo.date_in %}
                            <td>{{individuo.date_in}}</td>     
                        {% else %}
                            <td>Sin datos</td>
                        {% endif %}
                        {% if individuo.date_out %}
                            <td>{{individuo.date_out}}</td>     
                        {% else %}
                            <td>Sin datos</td>
                        {% endif %}
                    </tr>  
                {% endfor %}              
            </table>
            <div class="btn-container">
                <button class="cons-Btn"><a href="{% url 'app:ImplicarIndi_view' info.id %}">Implicar afiliado a un proceso</a></button>
            </div>
        </div>
    </div>
</body>
{% endblock %}

app/templates/app/consAPro.html
{% extends "app/templateIn.html" %}

{% block Administrar %}
    {% if request.user.is_superuser == 0 %}
        <li style="display: none;" class="li-start"><a href="#">Administrar</a>
    {% else %}
        <li class="li-start"><a href="#">Administrar</a>
    {% endif %}
{% endblock %}

{% block contenido %}
<body>
    <div class="inf-container">
        <div class="inf">
            <span>Consultar Proceso</span>
            <p>Informacion del Proceso</p>
            <table>
                <thead>
                    <tr>
                        <th>Titulo</th><th>Fecha de inicio</th><th>Estado</th><th>Entidad</th><th>Monto</th><th>Comentarios del proceso</th><th>Cantidad de vistas</th>
                    </tr>
                </thead>
                        <tr>
                            <td>{{info.title}}</td>
                            <td>{{info.date_start}}</td>
                            <td>
                                {% if info.state %}
                                    Abierto
                                {% else %}
                                    Cerrado
                                {% endif %}
                            </td>
                            <td>{{info.entity}}</td>
                            <td>{{info.howmuch}}</td>
                            <td>{{info.comments}}</td>
                            <td>{{info.views}}</td>
                        </tr>               
            </table>
            <span>Lista de implicados</span>
            <table>
                <thead>
                    
                    <tr>
                        <th>Apellidos</th>
                        <th>Nombres</th>
                        <th>Partido político</th>
                        <th>Fecha de acusación</th>
                        <th>Acusación</th>
                        <th>Declarado</th>
                        <th>Pena</th>
                        <th>Comentarios</th>
                    </tr>
                </thead>
                    {% for dato in lista %}
                        <tr>
                            <td>{{dato.lastname}}</td>
                            <td>{{dato.name}}</td>
                            <td>{{dato.part}}</td>
                            <td>
                                {% if dato.date_imp %}
                                    {{dato.date_imp}}
                                {% else %}
                                    Sin informacion
                                {% endif %}
                            </td>
                            <td>
                                {% if dato.charge %}
                                    {{dato.charge}}
                                {% else %}
                                    Sin informacion
                                {% endif %}  
                            </td>
                            <td>
                                {% if dato.guilty %}
                                    {{dato.guilty}}
                                {% else %}
                                    Sin informacion
                                {% endif %}  
                            </td>
                            <td>
                                {% if dato.sentence %}
                                    {{dato.sentence}}
                                {% else %}
                                    Sin informacion
                                {% endif %}  
                            </td>
                            <td>
                                {% if dato.commnts %}
                                    {{dato.commnts}}
                                {% else %}
                                    Sin informacion
                                {% endif %}  
                            </td>
                        </tr>
                    {% endfor %}                 
            </table>
        </div>
    </div>
</body>
{% endblock %}

app/templates/app/consPart.html
{% extends "app/templateIn.html" %}

{% block Administrar %}
    {% if request.user.is_superuser == 0 %}
        <li style="display: none;" class="li-start"><a href="#">Administrar</a>
    {% else %}
        <li class="li-start"><a href="#">Administrar</a>
    {% endif %}
{% endblock %}

{% block contenido %}
<body>
    <div class="inf-container">
        <div class="inf">
            <span>Lista de Partidos Políticos</span>
            <p></p>
            <table>
                <thead>
                    <tr>
                        <th>Nombre</th><th>Cantidad de visitas</th><th>Cantidad de procesos</th>
                    </tr>
                </thead>
                    {% for dato in lista %}
                        <tr>
                            <td><a href="{% url 'app:consAPart_view' dato.partido.id %}">{{ dato.partido.nameP}}</a></td>
                            <td>{{dato.partido.views}}</td>
                            <td>{{dato.how}}</td>
                        </tr>               
                    {% endfor %}
            </table>
        </div>
    </div>
</body>
{% endblock %}

app/templates/app/creaIndiv.html
{% extends "app/templateIn.html" %}

{% block Administrar %}
    {% if request.user.is_superuser == 0 %}
        <li style="display: none;" class="li-start"><a href="#">Administrar</a>
    {% else %}
        <li class="li-start"><a href="#">Administrar</a>
    {% endif %}
{% endblock %}

{% block contenido %}
<body>
    <div class="form-container">
        <div class="welcome-container">
            <span>Crear individuo</span>
            <hr>
            <p></p>
            <div class="forms">
                <form action="{% url 'app:creaIndiv_post' %}" method="post" id="form-log" class="form">
                    {% csrf_token %} 
                    <fieldset>
                        <label for="">Apellidos</label>
                        <input type="text" name="indiv_lastname" id="indiv-lastname" placeholder="Ingrese los Apellidos" required>
                    </fieldset>
                    <fieldset>
                        <label for="">Nombres</label>
                        <input type="text" name="indiv_name" id="indiv-name" placeholder="Ingrese los Nombres" required>
                    </fieldset>
                    <fieldset>
                        <label for="">Fecha de nacimiento</label>
                        <input type="date" name="birthday" id="birthday">
                    </fieldset>
                    <fieldset>
                        <button type="submit">Enviar</button>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</body>
{% endblock %}

app/templates/app/creaPart.html
{% extends "app/templateIn.html" %}

{% block Administrar %}
    {% if request.user.is_superuser == 0 %}
        <li style="display: none;" class="li-start"><a href="#">Administrar</a>
    {% else %}
        <li class="li-start"><a href="#">Administrar</a>
    {% endif %}
{% endblock %}

{% block contenido %}
    <body>
        <div class="form-container">
            <div class="welcome-container">
                <span>Crear Partido</span>
                <hr>
                <p>Crear un partido político que agrupe individuos</p>
                <div class="forms">
                    <form action="{% url 'app:creaPart_post' %}" method="POST" id="form-log" class="form">
                        {% csrf_token %}
                        <fieldset>
                            <label for="">Nombre</label>
                            <input type="text" name="nameP" id="nameP" placeholder="Nombre del partido" required>
                        </fieldset>
                        <fieldset>
                            <button type="submit">Enviar</button>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </body>
{% endblock %}

app/templates/app/creaPro.html
{% extends "app/templateIn.html" %}

{% block Administrar %}
    {% if request.user.is_superuser == 0 %}
        <li style="display: none;" class="li-start"><a href="#">Administrar</a>
    {% else %}
        <li class="li-start"><a href="#">Administrar</a>
    {% endif %}
{% endblock %}

{% block contenido %}
<body>
    <div class="form-container">
        <div class="welcome-container">
            <span>Crear Proceso</span>
            <hr>
            <p>Crea un proceso en la plataforma para posteriormente asociar afiliados a partidos políticos</p>
            <div class="forms">
                <form action="{% url 'app:creaPro_post' %}" method="post" id="form-log" class="form">
                    {% csrf_token %}
                    <fieldset>
                        <label for="">Titulo</label>
                        <input type="text" name="title" id="title" placeholder="Ingrese titulo" required>
                    </fieldset>

                    <fieldset>
                        <label for="">Fecha de inicio</label>
                        <input type="date" name="date_start" id="date_start" required>
                    </fieldset>

                    <fieldset>
                        <label for="">Fecha de finalización</label>
                        <input type="date" name="date_end" id="date_end">
                    </fieldset>

                    <fieldset>
                        <label for="">Estado del Proceso</label>
                        <select name="state" id="state">
                            <option value="on">Abierto</option>
                            <option value="off">Cerrado</option>
                        </select>
                    </fieldset>

                    <fieldset>
                        <label for="">Entidad</label>
                        <input type="text" name="entity" id="entity" placeholder="Ingrese la entidad"required>
                    </fieldset>

                    <fieldset>
                        <label for="">Monto</label>
                        <input type="number" name="howmuch" id="howmuch" placeholder="Ingrese el monto en pesos">
                    </fieldset>

                    <fieldset>
                        <label for="">Comentarios</label>
                        <input type="text" name="comments" id="comments" placeholder="Añada sus comentarios">
                    </fieldset>

                    <fieldset>
                        <button type="submit">Enviar</button>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</body>
{% endblock %}

app/templates/app/editProfile.html
{% extends "app/templateIn.html" %}

{% block Administrar %}
    {% if request.user.is_superuser == 0 %}
        <li style="display: none;" class="li-start"><a href="#">Administrar</a>
    {% else %}
        <li class="li-start"><a href="#">Administrar</a>
    {% endif %}
{% endblock %}

{% block contenido %}
    <body>
        <div class="form-container">
            <div class="welcome-container">
                <span>Editar Perfil</span>
                <hr>
                <p>Modifique los campos que desee cambiar</p>
                <div class="forms">
                    <form action="{% url 'app:editProfile_post' %}" method="post" class="form" >
                        {% csrf_token %}
                        <fieldset>
                            <label for="">Usuario</label>
                            <input type="text" name="username" id="username" value="{{ request.user.username }}" required>
                        </fieldset>
                        <fieldset>
                            <label for="">Contraseña</label>
                            <input type="password" name="password" id="password" value="{{ request.user.password }}" required>
                        </fieldset>
                        <fieldset>
                            <label for="">Correo</label>
                            <input type="email" name="email" id="email" value="{{ request.user.email }}" required>
                        </fieldset>
                        <fieldset>
                            <label for="">Nombre</label>
                            <input type="text" name="name" id="name" value="{{ request.user.first_name }}" required>
                        </fieldset>
                        <fieldset>
                            <label for="">Apellidos</label>
                            <input type="text" name="lastname" id="lastname" value="{{ request.user.last_name }}"  required>
                        </fieldset>
                        <fieldset>
                            <button type="submit">Enviar</button>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </body>
{% endblock %}

app/templates/app/login.html
{% extends "app/templateOut.html" %}
{% block titulo %} 
    Iniciar sesión               
{% endblock %}

{% block info %}
    Escriba sus credenciales de ingreso
{% endblock %}

{% block contenido %}
    <div class="forms">
        <form action="{% url 'app:login_post' %}" method="POST" id="form-log" class="form">
            {% csrf_token %} 
            <fieldset>
                <label for="">Usuario</label>
                <input type="text" name="username" id="username" placeholder="Ingrese su usuario" required>
            </fieldset>
            <fieldset>
                <label for="">Contraseña</label>
                <input type="password" name="password" id="password" placeholder="Ingrese su contraseña" required>
            </fieldset>
            <fieldset>
                <button type="submit">Enviar</button>
            </fieldset>
        </form>
    </div>
{% endblock %}

app/templates/app/templateIn.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'app/styles.css' %}">
    <title>Hechos de Corrupción Gubernamental</title>
</head>
<header class="header">
    <div class="head-title">
        <a href="{% url 'app:index' %}">
            <h1>Hechos de Corrupción Gubernamental</h1>
        </a>
    </div>
    <nav class="nav">
        <ul class="ul-start">
            {% block Administrar %}{% endblock %}
                <ul class="drop">
                    <ul class="drop">
                        <li><a href="{% url 'app:creaPart_view' %}">Crear Partido</a></li>
                        <li><a href="{% url 'app:aproPro_view' %}">Aprobar Proceso</a></li>
                        <li><a href="{% url 'app:aproAfil_view' %}">Aprobar Afiliación</a></li>
                        <li><a href="{% url 'app:habiCiuda_view' %}">Habilitar ciudadano</a></li>
                    </ul>
                </ul>
            </li>
            <li class="li-start"><a href="#">Creacion</a>
                <ul class="drop">
                    <li><a href="{% url 'app:creaIndiv_view' %}">Crear Individuo</a></li>
                    <li><a href="{% url 'app:creaPro_view' %}">Crear Proceso</a></li>
                </ul>
            </li>
            <li class="li-start"><a href="#">Consulta</a>
                <ul class="drop">
                    <li><a href="{% url 'app:consIndiv_view' %}">Lista de individuos</a></li>
                    <li><a href="{% url 'app:consPart_view' %}">Lista de Partidos</a></li>
                </ul>
            </li>
            <li class="li-start"><a href="#">Perfil</a>
                <ul class="drop">
                    <li><a href="{% url 'app:editProfile_view' %}">Cambiar datos de cuenta</a></li>
                    <li><a href="{% url 'app:logout_' %}">Cerrar sesión</a></li>
                </ul>
            </li>
        </ul>
        </div>
    </nav>
</header>
{% block contenido %}
{% endblock %}
<footer>
    <ul>
        <li>Profesor: John Alexander Cardozo Ramírez</li>
        <li><a href="https://www.usta.edu.co">Univesidad Santo Tomás</a></li>
    </ul>
</footer>

</html>

app/templates/app/templateOut.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'app/styles.css' %}">
    <title>Hechos de Corrupción Gubernamental</title>
</head>
<header class="header">
    <div class="head-title">
        <a href="#">
            <h1>Hechos de Corrupción Gubernamental</h1>
        </a>
    </div>
    <nav class="nav">
        <ul class="ul-start">
            <li class="li-start"><a href="{% url 'app:login_view' %}">Iniciar sesión</a></li>
            <li class="li-start"><a href="{% url 'app:startup_view' %}">Registrarse</a></li>
        </ul>
        </div>
    </nav>
</header>

<body>
    <div class="form-container">
        <div class="welcome-container">
            <span>
                {% block titulo %}
                {% endblock %}
            </span>
            <hr>
            <p>
                {% block info %}
                {% endblock %}
            </p>
            {% block contenido %}
            {% endblock %}
        </div>
    </div>
</body>
<footer>
    <ul>
        <li>Profesor: John Alexander Cardozo Ramírez</li>
        <li><a href="https://www.usta.edu.co">Univesidad Santo Tomás</a></li>
    </ul>
</footer>

</html>